
apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: face-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: face-app
    spec:
      containers:
        - image: mhelkeyappfolio/hackfolio2021-face-app:alpha-0.0.4
          imagePullPolicy: Always
          name: face-app
---
apiVersion: v1
kind: Service
metadata:
  name: face-app
  namespace: default
  labels:
    app: face-app
spec:
  ports:
    - name: http-port
      port: 42069
      targetPort: 42069
      protocol: TCP
  type: LoadBalancer